export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const PAGINATION = 'PAGINATION';
export const FILTER = 'FILTER';
export const EMPTY_FILTER = 'EMPTY_FILTER';
export const FILTER_CONTINENT = 'FILTER_CONTINENT';
export const FILTER_ORDER = 'FILTER_ORDER';
