export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const FILTER_COUNTRY = 'FILTER_COUNTRY';
export const ORDER_COUNTRY = 'ORDER_COUNTRY';
export const ORDER_POPULATION = 'ORDER_POPULATION';
export const PAGINATION = 'PAGINATION';
export const FILTER = 'FILTER';